import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'GreenHouse',
  description: 'Generated by HKT',
  icons: {
    icon: '/favicon.ico',
  },
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#DCEECB" }}>{children}</body>
    </html>
  )
}
