'use client'
import { Inter } from 'next/font/google'
import AppSidebar from '@/components/app.sidebar'
import 'bootstrap/dist/css/bootstrap.min.css';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GreenHouse',
  description: 'Generated by HKT',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0, padding: 0, overflowX: 'auto', overflowY: 'hidden' }}>
        <Row style={{ margin: 0, width: '100vw', height: '100vh' }}>
          <Col xs="auto" style={{ height: '100vh', overflowY: 'auto' }}>
            <AppSidebar />
          </Col>
          <Col xs={8} md={10} style={{ background: '#DCEECB', height: '100vh', overflowX: 'auto' }}>
            {children}
          </Col>
        </Row>
      </body>
    </html>

  )
}
